// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2Z9fyUJN_eNBVKeIFHR5DZcIfP50CMM',
    appId: '1:968592351311:web:55138885b139823da30a3a',
    messagingSenderId: '968592351311',
    projectId: 'mydogapp-35bed',
    authDomain: 'mydogapp-35bed.firebaseapp.com',
    storageBucket: 'mydogapp-35bed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lUjZijDxQNtcEXulzjnm6GJ4KRvu4l0',
    appId: '1:968592351311:android:f8757623210d633aa30a3a',
    messagingSenderId: '968592351311',
    projectId: 'mydogapp-35bed',
    storageBucket: 'mydogapp-35bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuj6KWOdoDBZf8XqmLRJXZMQPXgokUzJ0',
    appId: '1:968592351311:ios:053c8ed88759b235a30a3a',
    messagingSenderId: '968592351311',
    projectId: 'mydogapp-35bed',
    storageBucket: 'mydogapp-35bed.firebasestorage.app',
    iosBundleId: 'com.example.myDogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuj6KWOdoDBZf8XqmLRJXZMQPXgokUzJ0',
    appId: '1:968592351311:ios:053c8ed88759b235a30a3a',
    messagingSenderId: '968592351311',
    projectId: 'mydogapp-35bed',
    storageBucket: 'mydogapp-35bed.firebasestorage.app',
    iosBundleId: 'com.example.myDogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT2Z9fyUJN_eNBVKeIFHR5DZcIfP50CMM',
    appId: '1:968592351311:web:7fdf03dfab278547a30a3a',
    messagingSenderId: '968592351311',
    projectId: 'mydogapp-35bed',
    authDomain: 'mydogapp-35bed.firebaseapp.com',
    storageBucket: 'mydogapp-35bed.firebasestorage.app',
  );
}
